### ISSUE TITLE
Delete repo

### ISSUE THREAD

**Issue by rbalet** [denniske/ngx-translate-multi-http-loader-demo#2]
Hi there. 

I've created a [new demo](https://stackblitz.com/edit/ngx-translate-multi-http-loader-sample-2clau3?file=src/app/app.module.ts) with the latest Angular version.

I'll be removing your version from the README.md file.

Feel free to delete this repo since it won't be used anymore ;)

Cheers!

**Comment by denniske** [comment]
Sounds good. Will delete
